apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: all-micro-ingress
spec:
  rules:
  - http:
      paths:
      - path: project/auth/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 3001

      - path: project/product/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: pproduct-service
            port:
              number: 3000