name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: project-1-400619
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: Set Kubectl Context
        run: gcloud container clusters get-credentials testing --zone us-central1 --project project-1-400619

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i localhost, -e "ansible_python_interpreter=$(which python)" ansible/kube_state_check.yaml -e 'ANSIBLE_HOST_KEY_CHECKING=False'

      - name: Create ingress Service
        run: |
          kubectl apply -f ingress.yaml
